apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: website
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: website
    spec:
      containers:
      - image: netsaj/lhk-chapter8:v1
        name: lhk-chapter8
        imagePullPolicy: Always
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: website
  name: website
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: website
  type: ClusterIP
status:
  loadBalancer: {}
