apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"linkerd.io/v1alpha2","kind":"ServiceProfile","metadata":{"annotations":{},"creationTimestamp":null,"name":"books.booksapp.svc.cluster.local","namespace":"booksapp"},"spec":{"routes":[{"condition":{"method":"GET","pathRegex":"/books\\.json"},"name":"GET /books.json"},{"condition":{"method":"POST","pathRegex":"/books\\.json"},"name":"POST /books.json"},{"condition":{"method":"DELETE","pathRegex":"/books/[^/]*\\.json"},"name":"DELETE /books/{id}.json"},{"condition":{"method":"GET","pathRegex":"/books/[^/]*\\.json"},"name":"GET /books/{id}.json"},{"condition":{"method":"PUT","pathRegex":"/books/[^/]*\\.json"},"name":"PUT /books/{id}.json"}]}}
  creationTimestamp: "2020-05-28T22:05:58Z"
  generation: 1
  name: books.booksapp.svc.cluster.local
  namespace: booksapp
  resourceVersion: "247913"
  selfLink: /apis/linkerd.io/v1alpha2/namespaces/booksapp/serviceprofiles/books.booksapp.svc.cluster.local
  uid: 222e017d-b20b-4503-8fdf-fc1601dd9c2e
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /books\.json
    name: GET /books.json
  - condition:
      method: POST
      pathRegex: /books\.json
    name: POST /books.json
  - condition:
      method: DELETE
      pathRegex: /books/[^/]*\.json
    name: DELETE /books/{id}.json
  - condition:
      method: GET
      pathRegex: /books/[^/]*\.json
    name: GET /books/{id}.json
  - condition:
      method: PUT
      pathRegex: /books/[^/]*\.json
    name: PUT /books/{id}.json
    timeout: 30ms
